# Generated by Django 4.2.2 on 2024-06-05 03:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0003_alter_articulo_precio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrito',
            new_name='Carritos',
        ),
    ]
